/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.tarea4.usermanager.views;

import java.awt.Color;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import com.tarea4.usermanager.controllers.UserController;
import com.tarea4.usermanager.models.User;
import com.tarea4.usermanager.utils.PasswordUtils;

/**
 *
 * @author angel
 */
public class UserFormDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(UserFormDialog.class.getName());
    // Controlador de usuario
    private UserController controller = new UserController();
    // Usuario actual (para editar) - Siempre que sea null, se creara uno nuevo
    private User currentUser = null;

    /**
     * Creates new form UserFormDialog
     */
    public UserFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Agregar estilos de placeholder a los campos de texto
        addPlaceholderStyle(txtFirstname, "Ingrese su nombre");
        addPlaceholderStyle(txtLastname, "Ingrese su apellido");
        addPlaceholderStyle(txtEmail, "Ingrese su correo");
        addPlaceholderStyle(txtPhone, "Ingrese su telefono");
        addPlaceholderStyle(txtUsername, "Ingrese su nombre de usuario");
        addPlaceholderStyle(txtPassword, "Ingrese su contraseña");
        addPlaceholderStyle(txtCheckPass, "Confirme su contraseña");
    }

    // Constructor sobrecargado para editar un usuario existente
    public UserFormDialog(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();

        // Si se le pasa un usuario, quiere decir que presiono el boton de editar
        this.currentUser = user;
        // Por ende cambio el texto del header del formulario y del boton de guardar
        lblNewUser.setText("EDITAR USUARIO");
        btnSaveUser.setText("Guardar Cambios");
        lblPassword.setText("Contraseña Actual");
        lblCheckPass.setText("Nueva Contraseña");

        // Y lleno los campos con la info del usuario
        txtFirstname.setText(user.getFirstname());
        txtLastname.setText(user.getLastname());
        txtEmail.setText(user.getEmail());
        txtPhone.setText(user.getPhoneNumber());
        txtUsername.setText(user.getUsername());
        // La contraseña no se rellenara

        // Agregar estilos de placeholder a los campos de texto
        addPlaceholderStyle(txtFirstname, "Ingrese su nombre");
        addPlaceholderStyle(txtLastname, "Ingrese su apellido");
        addPlaceholderStyle(txtEmail, "Ingrese su correo");
        addPlaceholderStyle(txtPhone, "Ingrese su telefono");
        addPlaceholderStyle(txtUsername, "Ingrese su nombre de usuario");
        addPlaceholderStyle(txtPassword, "Ingrese su contraseña actual");
        addPlaceholderStyle(txtCheckPass, "Ingrese una nueva contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblNewUser = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblCheckPass = new javax.swing.JLabel();
        txtCheckPass = new javax.swing.JPasswordField();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnSaveUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(245, 245, 247));

        pnlHeader.setBackground(new java.awt.Color(46, 58, 89));

        lblNewUser.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNewUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewUser.setText("NUEVO USUARIO");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(lblNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Nombre de Usuario");

        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setPreferredSize(new java.awt.Dimension(250, 32));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setPreferredSize(new java.awt.Dimension(250, 32));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Contraseña");

        txtPassword.setPreferredSize(new java.awt.Dimension(250, 32));

        lblCheckPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCheckPass.setText("Confirmar Contraseña");

        txtCheckPass.setPreferredSize(new java.awt.Dimension(250, 32));

        lblFirstname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstname.setText("Nombre");

        txtFirstname.setForeground(new java.awt.Color(153, 153, 153));
        txtFirstname.setPreferredSize(new java.awt.Dimension(250, 32));

        lblLastname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastname.setText("Apellido");

        txtLastname.setForeground(new java.awt.Color(153, 153, 153));
        txtLastname.setPreferredSize(new java.awt.Dimension(250, 32));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setText("Telefono");

        txtPhone.setForeground(new java.awt.Color(153, 153, 153));
        txtPhone.setPreferredSize(new java.awt.Dimension(250, 32));

        btnSaveUser.setBackground(new java.awt.Color(74, 144, 226));
        btnSaveUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveUser.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveUser.setText("Guardar");
        btnSaveUser.setPreferredSize(new java.awt.Dimension(220, 38));
        btnSaveUser.addActionListener(this::btnSaveUserActionPerformed);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCheckPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContainerLayout.createSequentialGroup()
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheckPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblFirstname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblLastname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblCheckPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCheckPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSaveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Agregar estilo de placeholder a un JTextField
    private void addPlaceholderStyle(JTextField textField, String placeholder) {

        // Solo aplicar placeholder si el campo está vacío
        if (textField.getText().trim().isEmpty()) {
            // Aplicar el placeholder y el color gris
            textField.setText(placeholder);
            textField.setForeground(new Color(150, 150, 150));
        } else {
            // Si ya tiene texto, mantener el color negro
            textField.setForeground(Color.BLACK);
        }

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                // Quitar el placeholder al enfocar el campo
                if (textField.getForeground().equals(new Color(150, 150, 150)) &&
                        textField.getText().equals(placeholder)) {

                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                // Restaurar el placeholder si el campo queda vacío al perder el foco
                if (textField.getText().trim().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(new Color(150, 150, 150));
                }
            }
        });
    }

    // Agregar estilo de placeholder a un JPasswordField
    private void addPlaceholderStyle(JPasswordField passwordField, String placeholder) {

        String text = new String(passwordField.getPassword());

        // Solo aplicar placeholder si está vacío
        if (text.trim().isEmpty()) {
            // Aplicar el placeholder y el color gris y el echo char en 0
            passwordField.setEchoChar((char) 0);
            passwordField.setText(placeholder);
            passwordField.setForeground(new Color(150, 150, 150));
        } else {
            // Si ya tiene texto, mantener
            passwordField.setForeground(Color.BLACK);
        }

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                String pass = new String(passwordField.getPassword());

                // Quitar el placeholder al enfocar el campo
                if (passwordField.getForeground().equals(new Color(150, 150, 150)) &&
                        pass.equals(placeholder)) {

                    passwordField.setText("");
                    passwordField.setEchoChar('•');
                    passwordField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                String pass = new String(passwordField.getPassword());

                // Restaurar el placeholder si el campo queda vacío al perder el foco
                if (pass.trim().isEmpty()) {
                    passwordField.setEchoChar((char) 0);
                    passwordField.setText(placeholder);
                    passwordField.setForeground(new Color(150, 150, 150));
                }
            }
        });
    }

    // Obtener el valor real de un campo, ignorando el placeholder
    public String getFieldWithoutPlaceholder(JTextField textField, String placeholder) {
        String text = textField.getText();
        return text.equals(placeholder) ? "" : text;
    }
    public String getFieldWithoutPlaceholder(JPasswordField passwordField, String placeholder) {
        String text = new String(passwordField.getPassword());
        return text.equals(placeholder) ? "" : text;
    }

    private void btnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveUserActionPerformed
        // Obtener los datos del formulario
        String firstname = getFieldWithoutPlaceholder(txtFirstname, "Ingrese su nombre");
        String lastname = getFieldWithoutPlaceholder(txtLastname, "Ingrese su apellido");
        String email = getFieldWithoutPlaceholder(txtEmail, "Ingrese su correo");
        String phoneNumber = getFieldWithoutPlaceholder(txtPhone, "Ingrese su telefono");
        String username = getFieldWithoutPlaceholder(txtUsername, "Ingrese su nombre de usuario");

        // Si currentUser es null, entonces es un nuevo usuario
        if (currentUser == null) {
            String password = getFieldWithoutPlaceholder(txtPassword, "Ingrese su contraseña");
            String confirmPassword = getFieldWithoutPlaceholder(txtCheckPass, "Confirme su contraseña");

            // Validar que las contraseñas coincidan
            if (!password.equals(confirmPassword)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Lógica para guardar un nuevo usuario
            try {
                // Llamar al controlador para crear el usuario
                controller.createUser(firstname, lastname, email, phoneNumber, username, password, confirmPassword);

                // Mostrar mensaje de éxito
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario creado con éxito", "Exito",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Cerrar el diálogo al guardar con éxito
                this.dispose();

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                logger.log(java.util.logging.Level.SEVERE, "Error al crear el usuario", e);
            }
        } else {
            String password = getFieldWithoutPlaceholder(txtPassword, "Ingrese su contraseña actual");
            String newPassword = getFieldWithoutPlaceholder(txtCheckPass, "Ingrese una nueva contraseña");

            // Validar que la contraseña actual sea correcta comparando hashes
            // TODO: fallback para que sea compatible con usuarios con contraseñas sin hash
            // Ya que asi esta en la bd de almacenitla
            if (password.equals(currentUser.getPassword()) || PasswordUtils.compare(password, currentUser.getPassword())) {
                // Lógica para actualizar un usuario existente
                try {
                        // Llamar al controlador para actualizar el usuario
                        controller.updateUser(currentUser.getUsername(), firstname, lastname, email, phoneNumber, username, newPassword);
                        
                        // Mostrar mensaje de éxito
                        javax.swing.JOptionPane.showMessageDialog(this, "Usuario actualizado con éxito", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        
                        // Cerrar el diálogo al guardar con éxito
                        this.dispose();
                } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                        logger.log(java.util.logging.Level.SEVERE, "Error al actualizar el usuario", e);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "La contraseña actual no es correcta", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }// GEN-LAST:event_btnSaveUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UserFormDialog dialog = new UserFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveUser;
    private javax.swing.JLabel lblCheckPass;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPasswordField txtCheckPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
