/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tarea4.usermanager.views;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import com.tarea4.usermanager.controllers.UserController;
import com.tarea4.usermanager.models.User;

/**
 *
 * @author angel
 */
public class UserManagementView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(UserManagementView.class.getName());
    private UserController controller = new UserController();

    /**
     * Creates new form LoginView
     */
    public UserManagementView() {
        initComponents();
        // Personalizar la tabla de usuarios
        customizeTable();
        // Desactivar la edicion directa de las celdas de la JTable
        tblUsers.setDefaultEditor(Object.class, null);
        // Cargar los usuarios en la tabla al iniciar la vista
        loadUsersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblUserManagement = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        lblUserList = new javax.swing.JLabel();
        scrollUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnCreateUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(245, 245, 247));
        pnlMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlHeader.setBackground(new java.awt.Color(46, 58, 89));

        lblUserManagement.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblUserManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserManagement.setText("USUARIOS REGISTRADOS");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(lblUserManagement)
                .addGap(294, 294, 294))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));

        lblUserList.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblUserList.setForeground(new java.awt.Color(51, 51, 51));
        lblUserList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserList.setText("Lista de Usuarios");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "Correo", "Usuario"
            }
        ));
        tblUsers.setGridColor(new java.awt.Color(255, 255, 255));
        scrollUsers.setViewportView(tblUsers);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(lblUserList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUserList)
                .addGap(18, 18, 18)
                .addComponent(scrollUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnCreateUser.setBackground(new java.awt.Color(74, 144, 226));
        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUser.setText("NUEVO");
        btnCreateUser.setPreferredSize(new java.awt.Dimension(110, 32));
        btnCreateUser.addActionListener(this::btnCreateUserActionPerformed);

        btnUpdateUser.setBackground(new java.awt.Color(74, 144, 226));
        btnUpdateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setText("ACTUALIZAR");
        btnUpdateUser.setPreferredSize(new java.awt.Dimension(110, 32));
        btnUpdateUser.addActionListener(this::btnUpdateUserActionPerformed);

        btnDeleteUser.setBackground(new java.awt.Color(217, 83, 79));
        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("ELIMINAR");
        btnDeleteUser.setPreferredSize(new java.awt.Dimension(110, 32));
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        btnLogout.setBackground(new java.awt.Color(46, 58, 89));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Cerrar Sesión");
        btnLogout.setPreferredSize(new java.awt.Dimension(110, 32));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Personalizar la apariencia de la tabla
    private void customizeTable() {
        // Configuraciones generales de la tabla
        tblUsers.setRowHeight(28); // Altura de las filas
        tblUsers.setFont(new Font("Segoe UI", Font.PLAIN, 13)); // Fuente de las celdas
        tblUsers.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14)); // Fuente del encabezado

        tblUsers.setShowGrid(false); // Ocultar las lineas de la cuadrícula
        tblUsers.setIntercellSpacing(new Dimension(0, 0)); // Eliminar espacio entre celdas

        tblUsers.getTableHeader().setBackground(new Color(48, 63, 159)); // Color de fondo del encabezado
        tblUsers.getTableHeader().setForeground(Color.WHITE); // Color de texto del encabezado

        // Renderizador personalizado para filas con colores alternados
        tblUsers.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
                // Reescribir el metodo para personalizar la apariencia de las celdas
                @Override
                public Component getTableCellRendererComponent(
                        JTable table, Object value, boolean isSelected,
                        boolean hasFocus, int row, int col) {
                                // Llamar al metodo original para obtener la celda predeterminada
                    Component c = super.getTableCellRendererComponent(
                            table, value, isSelected, hasFocus, row, col);

                            // Aplicar colores alternados a las filas
                    if (!isSelected) {
                        // Color de fondo para filas pares (GRIS) e impares (BLANCO) texto (NEGRO)
                        c.setBackground(row % 2 == 0
                                ? new Color(245, 245, 245)
                                : Color.WHITE);
                        c.setForeground(Color.BLACK);
                    } else {
                        // Si se selecciona esa fila
                        // Cambiar el background a AZUL y el texto a BLANCO
                        c.setBackground(new Color(66, 133, 244));
                        c.setForeground(Color.WHITE);
                    }

                    // Retornar el componente modificado
                    return c;
                }
        });
}

    // Cargar los usuarios en la tabla
    private void loadUsersTable() {
        try {
            // Obtener el modelo de la tabla actual
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();

            // Limpiar las filas existentes de usuarios
            model.setRowCount(0);

            // Obtener la lista de usuarios desde el controlador
            List<User> users = controller.getAllUsers();

            // Iterar entre todos los usuarios
            for (User user : users) {
                // Creo una fila con los datos del usuario
                Object[] rowData = {
                        user.getFirstname(),
                        user.getLastname(),
                        user.getPhoneNumber(),
                        user.getEmail(),
                        user.getUsername()
                };

                // Agrego la fila al modelo de la tabla
                model.addRow(rowData);
            }
        } catch (Exception e) {
            // Mostrar mensaje de error si falla la carga
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los usuarios: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateUserActionPerformed
        // Obtener la fila seleccionada
        int selectedRow = tblUsers.getSelectedRow();

        // Verificar si se selecciono una fila
        if (selectedRow == -1) {
            // Mostrar mensaje de error si no se selecciono ninguna fila
            JOptionPane.showMessageDialog(this, "Debes seleccionar un usuario valido para actualizar!");
            return;
        }

        // Obtener el username del usuario a actualizar
        String username = tblUsers.getValueAt(selectedRow, 4).toString();

        try {
            // Obtener los datos completos del usuario desde el controlador
            User user = controller.getUser(username);

            // Verificar si el usuario existe
            if (user == null) {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado!");
                return;
            }

            // Abrir el dialogo para actualizar el usuario, pasando los datos actuales
            UserFormDialog userFormDialog = new UserFormDialog(this, true, user);
            userFormDialog.setVisible(true);

            // Recargar la tabla de usuarios despues de cerrar el dialogo
            loadUsersTable();
        } catch (SQLException e) {
            // Mostrar mensaje de error si falla la carga
            JOptionPane.showMessageDialog(this,
                    "Error al obtener los datos del usuario: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }// GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
        // Mostrar la vista de login
        LoginView loginView = new LoginView();
        loginView.setVisible(true);

        // Cerrar la vista actual
        this.dispose();
    }// GEN-LAST:event_btnLogoutActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteUserActionPerformed
        // Obtener la fila seleccionada
        int selectedRow = tblUsers.getSelectedRow();

        // Verificar si se selecciono una fila
        if (selectedRow == -1) {
            // Mostrar mensaje de error si no se selecciono ninguna fila
            JOptionPane.showMessageDialog(this, "Debes seleccionar un usuario valido para eliminar!");
            return;
        }

        // Obtener el username del usuario a eliminar
        String username = tblUsers.getValueAt(selectedRow, 4).toString();

        // Mostrar mensaje de confirmacion
        int confirmChoice = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar el usuario " + username + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        // Si el usuario confirma la eliminacion
        if (confirmChoice == JOptionPane.YES_OPTION) {
            try {
                // Llamamos el controlador para eliminar el usuario
                controller.deleteUser(username);
            } catch (SQLException e) {
                // Mostrar mensaje de error si falla la eliminacion
                JOptionPane.showMessageDialog(this,
                        "Error al eliminar el usuario: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Luego, recargar la tabla de usuarios
            loadUsersTable();

            // Mostrar feedback de exito
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
        }
    }// GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateUserActionPerformed
        // Abrir el dialogo para crear un nuevo usuario
        UserFormDialog userFormDialog = new UserFormDialog(this, true);
        userFormDialog.setVisible(true);

        // Recargar la tabla de usuarios despues de cerrar el dialogo
        loadUsersTable();
    }// GEN-LAST:event_btnCreateUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagementView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JLabel lblUserList;
    private javax.swing.JLabel lblUserManagement;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane scrollUsers;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
